# Generated by Django 3.2.3 on 2021-12-17 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211217_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesoremoto',
            name='idEquipoIt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.equipoit', verbose_name='Equipo IT'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='idEquipoIt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.equipoit', verbose_name='Equipo IT'),
        ),
    ]
